### PR TITLE
[WIP] Node + Chromium support

### PR DESCRIPTION
**Pull request by ydnar**
* Node 9.5.0
* Yarn 1.3.2
* Labels including the versions of stuff we spec as ARGs.
* A bunch of extra commands which I want for diagnosis

### CODE REVIEW

**Comment by ydnar** [comment]
According to the Puppeteer docs, we need to install a few additional things to get [Puppeteer to run in Docker](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker).

**Comment by cee-dub** [comment]
Sorry about the new conflict, I took just the `git-hub` tool lines to master.

**Comment by ydnar** [comment]
`1.12-stretch-node-browsers` is a thing now: https://hub.docker.com/r/circleci/golang/tags

**Comment by ydnar** [comment]
https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/golang/images/1.12.0-stretch/Dockerfile

…and…

https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/golang/images/1.12.0-stretch/node-browsers/Dockerfile

**Comment by ydnar** [comment]
Closed in favor of #15.

**Pull request closed without merging**
